name: flutter_firebase_crud
description: A comprehensive Firebase CRUD library for Flutter applications
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies - minimal working versions
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  
  # Utility dependencies
  uuid: ^3.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: