name: foobar
description: A simple Dart IndexedDB CRUD example demonstrating webdev workflow
version: 1.0.0
publish_to: 'none' # Prevent accidental publishing

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  idb_shim: ^2.6.7
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.5
  lints: ^5.0.0
  test: ^1.25.0

# Optional: Add scripts for common commands
# Run with: dart run build_runner <command>
executables:
  build_runner: build_runner
