name: indexeddb_example
description: IndexedDB implementation of database service for browser applications
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # IndexedDB support for Dart web applications
  indexed_db: ^2.1.3
  
  # Utility packages
  uuid: ^3.0.7
  intl: ^0.18.1

dev_dependencies:
  # Testing framework
  test: ^1.21.0
  
  # Linting
  lints: ^2.0.0

# Platform configuration
platforms:
  web:

# This package is designed specifically for web browsers
# It uses IndexedDB which is only available in browser environments
