include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing return types as errors
    always_declare_return_types: error
    # Treat unnecessary imports as errors
    unnecessary_import: error
    # Treat unused imports as errors
    unused_import: error

linter:
  rules:
    # Code style
    - prefer_single_quotes
    - prefer_final_locals
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    
    # Documentation
    - public_member_api_docs
    - lines_longer_than_80_chars
    
    # Error handling
    - avoid_catching_errors
    - use_rethrow_when_possible
    
    # Performance
    - avoid_function_literals_in_foreach_calls
    - prefer_foreach
    - prefer_for_elements_to_map_fromIterable
    
    # Design
    - avoid_classes_with_only_static_members
    - prefer_mixin
    - avoid_implementing_value_types
    
    # Security
    - avoid_web_libraries_in_flutter
    
    # Maintenance
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    
    # Best practices
    - always_use_package_imports
    - avoid_print
    - prefer_relative_imports
