name: simple_database_api
description: A beginner-friendly database API for college freshmen learning programming
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # No external dependencies needed!
  # This API is designed to be simple and self-contained
  # Perfect for beginners who want to focus on learning concepts

dev_dependencies:
  # Development and testing tools
  test: ^1.21.0
  lints: ^2.0.0

# This package works on all platforms
platforms:
  linux:
  macos:
  windows:
  android:
  ios:
  web:

# Project metadata
homepage: https://github.com/your-university/ase456
repository: https://github.com/your-university/ase456/tree/main/database/api
documentation: https://github.com/your-university/ase456/blob/main/database/api/README.md

# Educational project information
topics:
  - education
  - database
  - api
  - beginners
  - dart
  - programming-concepts

# This is an educational project designed for:
# - College freshmen learning programming
# - Understanding database concepts
# - Learning API design patterns
# - Practicing software engineering principles

# How to use:
# 1. dart run demo.dart      (see examples)
# 2. dart run tutorial.dart  (step-by-step learning)
# 3. dart run exercises.dart (practice problems)
