name: foobar
description: Simple Firebase Foobar CRUD Demo for Students
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firedart: ^0.9.8
  # Firebase Core - Required for all Firebase services

dev_dependencies:
  test: ^1.21.0
  # Testing framework for unit tests
