name: sqlite_crud_demo
description: A simple CRUD application demonstrating SQLite operations in pure Dart
version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  sqlite3: ^2.4.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.21.0
