include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Disable some rules for educational code
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false  # Allow print statements for educational examples
    
    # Enable helpful rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
