name: pocketbase_student_example
description: A simple PocketBase example with Student CRUD operations
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # PocketBase client
  pocketbase: ^0.23.0
  
  # Utility packages
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0

# This is only needed if you plan to make this a Flutter app
# If pure Dart, you can remove this section
flutter:
  uses-material-design: true
