name: student
description: A simple student management system using IndexedDB
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Modern web package
  web: ^1.1.1
  
  # IndexedDB support for web applications
  idb_shim: any

dev_dependencies:
  # Build system for Dart web applications
  build_runner: ^2.3.3
  build_web_compilers: ^4.2.0
  
  # Linting
  lints: ^6.0.0

# Platform configuration
platforms:
  web:
