name: my_indexeddb_project
description: A simple Dart IndexedDB CRUD example
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  idb_shim: any
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.5
