#!/bin/bash

echo "🎯 WHERE IS THE JAVASCRIPT CODE THAT CALLS main()?"
echo "=================================================="
echo ""
echo "📝 Let's compile a tiny example and see..."

# Create a minimal Dart file
cat > minimal_example.dart << 'EOF'
void main() {
  print('Hello from main()!');
}
EOF

echo "📄 Our minimal Dart code:"
cat minimal_example.dart

echo ""
echo "🔧 Compiling to JavaScript..."
dart compile js minimal_example.dart -o minimal.js

if [ $? -eq 0 ]; then
    echo "✅ Compilation successful!"
    
    echo ""
    echo "📊 The compiled JavaScript file:"
    echo "   File: minimal.js"
    echo "   Size: $(ls -lh minimal.js | awk '{print $5}')"
    echo "   Lines: $(wc -l < minimal.js)"
    
    echo ""
    echo "🎯 THE MAGIC: Last 10 lines of minimal.js (where main() gets called):"
    echo "===================================================================="
    tail -10 minimal.js | nl -v $(( $(wc -l < minimal.js) - 9 ))
    
    echo ""
    echo "🔍 Searching for main() calls in the file:"
    echo "=========================================="
    grep -n "main(" minimal.js | tail -3
    
    echo ""
    echo "💡 KEY INSIGHT:"
    echo "==============="
    echo "The call to main() is AUTOMATICALLY ADDED by the Dart compiler"
    echo "at the end of the generated JavaScript file!"
    echo ""
    echo "So when your HTML loads:"
    echo "  <script src=\"main.dart.js\"></script>"
    echo ""
    echo "It's loading a JavaScript file that:"
    echo "  1. Contains all your Dart code converted to JavaScript"
    echo "  2. Ends with a call to main() - added by the compiler"
    echo "  3. Therefore main() executes when the JS file loads!"
    
    # Clean up
    rm -f minimal_example.dart minimal.js*
    
else
    echo "❌ Compilation failed"
fi

echo ""
echo "🧠 For Teaching Students:"
echo "========================"
echo "The 'invisible' JavaScript that calls main() is:"
echo "  - Generated by the Dart compiler (dart2js)"
echo "  - Embedded at the end of the .js file"
echo "  - Not visible in your HTML or Dart code"
echo "  - Automatically executed when the browser loads the JS file"
echo ""
echo "This is why main() is required - it's the entry point that"
echo "the generated JavaScript code calls to start your app!"
