name: pr
description: IndexedDB CRUD Operations Tutorial with Dart
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  indexed_db: ^1.0.1
  web: ^1.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  webdev: ^3.0.0
