name: foobar_dart
description: FooBar in Dart
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # IndexedDB support for Dart web applications
  indexed_db: ^1.0.1
  web: ^1.1.1  # or latest version  
  
dev_dependencies:
  # Testing framework
  test: ^1.26.3

# Platform configuration
platforms:
  web:

