name: universal_crud_api
description: A universal CRUD API that works with multiple database backends
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # HTTP server for API
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # HTTP client
  http: ^1.1.0
  
  # Database implementations
  sqlite3: ^2.4.0
  path: ^1.8.3
  
  # Firebase (optional - for Firebase implementation)
  # cloud_firestore: ^4.8.0
  # firebase_core: ^2.15.0
  
  # Utilities
  uuid: ^4.2.1
  
dev_dependencies:
  test: ^1.24.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

