// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSbJH_KjAlit7r5YgtEnL0ovx9_bgvw5o',
    appId: '1:827133271343:web:df08d3f04ca4968ca815da',
    messagingSenderId: '827133271343',
    projectId: 'foobar-a1317',
    authDomain: 'foobar-a1317.firebaseapp.com',
    storageBucket: 'foobar-a1317.firebasestorage.app',
    measurementId: 'G-5VN183B3VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCObLVYmFCmJ2FkT-ffVy7862L53kUWCSY',
    appId: '1:827133271343:android:ad32a20764c78659a815da',
    messagingSenderId: '827133271343',
    projectId: 'foobar-a1317',
    storageBucket: 'foobar-a1317.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiuqZiMwcF5OTLlgC04NT-Sy6KOyxSEMc',
    appId: '1:827133271343:ios:a1e3637cb8d62765a815da',
    messagingSenderId: '827133271343',
    projectId: 'foobar-a1317',
    storageBucket: 'foobar-a1317.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiuqZiMwcF5OTLlgC04NT-Sy6KOyxSEMc',
    appId: '1:827133271343:ios:a1e3637cb8d62765a815da',
    messagingSenderId: '827133271343',
    projectId: 'foobar-a1317',
    storageBucket: 'foobar-a1317.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSbJH_KjAlit7r5YgtEnL0ovx9_bgvw5o',
    appId: '1:827133271343:web:e323b59eebe265c4a815da',
    messagingSenderId: '827133271343',
    projectId: 'foobar-a1317',
    authDomain: 'foobar-a1317.firebaseapp.com',
    storageBucket: 'foobar-a1317.firebasestorage.app',
    measurementId: 'G-S6TMKYVMPF',
  );

}