name: db_abstraction_demo_mvvm
description: A Flutter demo application showing database abstraction patterns across SQLite, IndexedDB, and PocketBase

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Database dependencies
  sqflite: ^2.3.0  # Not available on web
  idb_shim: ^2.4.1+1  # Web-only
  http: ^1.1.0
  
  # State management and UI
  provider: ^6.1.1
  
  # Utilities
  uuid: ^4.1.0
  path: ^1.8.3  # For database path handling
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true
